spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/decisionfatigue
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
tmdb:
  apiKey: ba37ac7bbfcc296f6b5db28cfef6fe87